# network name
name = "PResNet18"

# imports for predictors
# imports = [
# "from torch.nn import Sequential, ReLU, ConvTranspose2d",
# ]

# uses PCoderN instead of PCoder
gradient_scaling = true

# uses shared hyperparameters across all PCoders
# it overwrites the hyperparameter values per PCoder and uses the default value
# or the values provided for the first PCoder
shared_hyperparameters = false

# input size [channels, height, width]
input_size = [3, 32, 32]

# pcoders
[[pcoders]]
module = "conv1"

[[pcoders]]
module = "layer1[1].conv2"

[[pcoders]]
module = "layer2[1].conv2"

[[pcoders]]
module = "layer3[1].conv2"

[[pcoders]]
module = "layer4[1].conv2"